// // // // // document.write("welcome");
// // // // // alert("hello");
// // // // // console.log(2);
// // // // var a = 2;
// // // // var b = 3;
// // // // var result = a+b;
// // // // console.log(result);
// // // var a = "hai";
// // // var b = " welcome "
// // // var result = b.length;
// // // console.log(result);
// // // console.log(typeof(a));
// // // var result1 = a.concat(b);
// // // console.log(result1);
// // // var result2 = a.toUpperCase();
// // // console.log(result2);
// // // var result3 = b.toLowerCase();
// // // console.log(result3);
// // // var result4 = b.trim();
// // // console.log(result4);

// // // var c = "hai, hello, welcome, hai";
// // // var result5 = c.indexOf("hai");
// // // console.log(result5);

// // // var d = "world hello welcome world";
// // // var result6 = d.lastIndexOf("world");
// // // console.log(result6);
// // // var result7 = d.search("hello");
// // // console.log(result7);
// // // var result8 = d.replace("world","change");
// // // console.log(result8);
// // // var result9 = d.charAt(0);
// // // console.log(result9);
// // // var result10 = d.charCodeAt(7);
// // // console.log(result10);
// // // var result11 = c.slice(0,10);
// // // console.log(result11);
// // // var result12 = c.substring(0,3);
// // // console.log(result12);
// // // var result13 = c.substr(5,14);
// // // console.log(result13);
// // var a = 2;
// // console.log(typeof(a));
// // var newresult = a.toString();
// // console.log(typeof(newresult));
// // var result1 = Number.MAX_VALUE;
// // console.log(result1);
// // var result2 = Number.MIN_VALUE;
// // console.log(result2);
// // var result3 = Number.POSITIVE_INFINITY;
// // console.log(result3);
// // var result4 = Number.NEGATIVE_INFINITY;
// // console.log(result4);
// // var result5 = Number.NaN;
// // console.log(result5);
// // var a = 10.33;
// // var result6 = parseInt(a);
// // console.log(result6);
// // var a = 12.334;
// // var result7 = parseFloat(a);
// // console.log(result7);
// // var a = 64;
// // var result8 = a.toExponential(2);
// // console.log(result8);
// // var a = 2.3;
// // var result9 = a.toFixed();
// // console.log(result9);
// // var a=3.3456;
// // var result10 = a.toPrecision(2);
// // console.log(result10);
// var fruits = ["Banana", "Orange", "Apple", "Mango"];
// var result = fruits.delete(0);
// console.log(result);
var fruits = ["Banana", "Orange", "Apple", "Mango"];
var result = fruits.splice(2, 0, "Lemon", "Kiwi");
console.log(result);

